version: '3.6'

services:
  api:
    container_name: fuzzy_trader_api
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=config.DevelopmentConfig
      - TEST_SETTINGS=config.TestingConfig
      - DATABASE_URL=postgres://postgres:postgres@db/trader_dev
      - TEST_DATABASE_URL=postgres://postgres:postgres@db/trader_test
      - JWT_ACCESS_TOKEN_EXPIRES=20
      - JWT_REFRESH_TOKEN_EXPIRES=30
      - JWT_SECRET_KEY=SECRETODEMAIS
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - '.:/src'

  db:
    container_name: fuzzy_trader_db
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:latest
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - default
    ports:
      - 5405:5432